- name: Install Java and JMeter
  hosts: slaves
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Download JMeter
      get_url:
        url: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
        dest: /tmp/apache-jmeter.tgz

    - name: Extract JMeter
      unarchive:
        src: /tmp/apache-jmeter.tgz
        dest: /opt/
        remote_src: yes

    - name: Create symlink
      file:
        src: /opt/apache-jmeter-5.6.2/bin/jmeter
        dest: /usr/bin/jmeter
        state: link
