- name: Install Java, JMeter, and Required Plugins
  hosts: slaves
  become: yes
  vars:
    jmeter_install_dir: /home/ubuntu/jmeter

  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Ensure JMeter base directory exists
      file:
        path: "{{ jmeter_install_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download JMeter
      get_url:
        url: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
        dest: /tmp/apache-jmeter.tgz

    - name: Extract JMeter to target dir
      unarchive:
        src: /tmp/apache-jmeter.tgz
        dest: "{{ jmeter_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: ubuntu
        group: ubuntu
