- name: Install Java and JMeter
  hosts: slaves
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Ensure target directory exists
      file:
        path: /home/ubuntu/jmeter
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download JMeter
      get_url:
        url: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
        dest: /tmp/apache-jmeter.tgz

    - name: Extract JMeter to /home/ubuntu/jmeter
      unarchive:
        src: /tmp/apache-jmeter.tgz
        dest: /home/ubuntu/jmeter
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: ubuntu
        group: ubuntu

    - name: Set lighter JVM heap in jmeter script
      replace:
        path: /home/ubuntu/jmeter/bin/jmeter
        regexp: 'HEAP=.*'
        replace: 'HEAP="-Xms256m -Xmx512m"'
      become: false

        - name: Clone BlazeMeter HLS Plugin repo
      git:
        repo: https://github.com/Blazemeter/HLSPlugin.git
        dest: /home/ubuntu/HLSPlugin
        force: yes
        update: yes
        version: master
      become_user: ubuntu

    - name: Build HLS Plugin using Gradle
      shell: ./gradlew jar
      args:
        chdir: /home/ubuntu/HLSPlugin
      become_user: ubuntu

    - name: Copy built HLS plugin to JMeter ext dir
      copy:
        src: /home/ubuntu/HLSPlugin/build/libs/HLSPlugin.jar
        dest: "{{ jmeter_install_dir }}/lib/ext/HLSPlugin.jar"
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy HLS plugin dependencies to JMeter lib
      shell: |
        ./gradlew copyDependencies
        cp build/dependencies/*.jar {{ jmeter_install_dir }}/lib/
      args:
        chdir: /home/ubuntu/HLSPlugin
      become_user: ubuntu
