- name: Run JMeter Test
  hosts: slaves
  tasks:
    - name: Run JMeter Test in Non-GUI Mode
      shell: |
        /home/ubuntu/jmeter/bin/jmeter -n \
        -t /home/ubuntu/practice-test.jmx \
        -l /home/ubuntu/result.jtl \
        -j /home/ubuntu/jmeter.log
      register: jmeter_output
      async: 1800
      poll: 10   # actively poll every 10s, shows output

    - name: Show JMeter logs
      shell: tail -n 20 /home/ubuntu/jmeter.log
      register: log_tail
      ignore_errors: yes

    - debug:
        msg: "{{ log_tail.stdout_lines }}"
        